name: Docker-Publish

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker build
        run: docker build -t ricardozambon/alura-curso-solid .

      - name: Push to DockerHub
        run: |
          docker tag ricardozambon/alura-curso-solid:latest ricardozambon/alura-curso-solid:${GITHUB_REF:11}
          docker push ricardozambon/alura-curso-solid:${GITHUB_REF:11}
          docker push ricardozambon/alura-curso-solid:latest